### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by peppe8o**
Added peppe8o.com post link to setup PiVPN and mail sending system for client profiles

### CODE REVIEW

**Comment by coolapso** [comment]
Hi thanks for doing that tutorial however, i have some concerns and I am not approving this to go for wider audience with our stamp on it. 

The reason for not approving it is mainly tied to the way the email part is handled, In your "how to setup exim" you are essentially teaching how to create a pure open spam email server,  to be honest I highly advise you to take that (exim) tutorial out!! 

Sorry if this sounds a bit harsh!! I highly value your effort!! but to me is a very huge danger to both security and privacy, even it being on a private network behind a router and firewall! 

I encourage you please to read more and understand more how email works behind the scenes, also most Email servers won't even accept that email as it will hit all the possible red flags there is to exist!

When it comes to email there is a lot that needs to be taken in consideration, in first place you don't even need an MTA to send an email like that, second you are setting up an open MTA with no security and privacy considerations at all, there is neither DKIM verification or SPF validation, there's neither encryption, so essentially the email goes out in the open and you have no way to tell that the email you just received in the spam box comes really from the same origin anymore! 

If you're open for improvement and suggestions, let me suggest you an alternative, 
Why don't you replace the exim tutorial by a tutorial on how to setup a cli email client with pgp encryption? and how to send the certificate with that? I Will be more than Happy to approve your how to install pivpn with that one instead!!! what you think @orazioedoardo ? I don't even think i have seen anyone taking this kind of approach yet! 

There are plenty of CLI email clients out there that can be used for this and will be way more secure and safer for all of us!!! 


Once again I really value your effort and i am sorry if i sound harsh but I really had to warn you and tell you how wrong that is! 

I will leave this open in case you are open for discussion and want to actually improve your tutorial!

**Comment by peppe8o** [comment]
Hi.
Thank you for dedicati dedicating your time to evaluate my post.

Honestly I don't share your opinion on MTA (otherwise every MTA open source software should be a spamming system) but I understand, respect and I'll honor it.
I'll change that post part using a text email client instead of an MTA and give you feedback when done (I suppose in a very few days).

Thank you again,
Giuseppe.

⁣Ottieni BlueMail per Android ​

Il giorno 29 Ott 2020, 22:13, alle ore 22:13, 4s3ti <notifications@github.com> ha scritto:

**Comment by coolapso** [comment]
@peppe8o Every MTA  setup by default is an open relay! and they simply do what they should! doesn't mean a default MTA is what you should use,  it simply is not the right tool for the job! and has a lot of implications to it on of them is that you just have no way to grant that the email and the certificate didn't got tampered or seen in trasit do you get my point? 

For example postfix, it comes with good default settings but after you install it there is a lot you need to do for it to be safe! an email server (MTA) is not something you just install, next next next and go, that one ... if it would be on the open internet side ...would be the juice spammers and hackers would be looking for to relay their phishing and spam stuff!

**Comment by peppe8o** [comment]
Hi,

my post has been updated changing MTA with a text based email client (Mutt).

Thank you for your suggestion, which is really appreciated.

 

Hope that this change can help in publishing my post link in PiVPN page.

 

Best regards,

Giuseppe

 

Giuseppe Cassibba

blog: peppe8o.com

twitter: @peppecassibba

linkedin: https://www.linkedin.com/in/giuseppe-cassibba-0312266

 

Da: 4s3ti <notifications@github.com> 
Inviato: venerdì 30 ottobre 2020 10:46
A: pivpn/pivpn.io <pivpn.io@noreply.github.com>
Cc: peppe8o <josephrm@inwind.it>; Mention <mention@noreply.github.com>
Oggetto: Re: [pivpn/pivpn.io] Update index.html (#3)

 

@peppe8o <https://github.com/peppe8o>  Every MTA setup by default is an open relay! and they simply do what they should! doesn't mean a default MTA is what you should use, it simply is not the right tool for the job! and has a lot of implications to it on of them is that you just have no way to grant that the email and the certificate didn't got tampered or seen in trasit do you get my point?

For example postfix, it comes with good default settings but after you install it there is a lot you need to do for it to be safe! an email server (MTA) is not something you just install, next next next and go, that one ... if it would be on the open internet side ...would be the juice spammers and hackers would be looking for to relay their phishing and spam stuff!

**Comment by coolapso** [comment]
Merged to test.. going to check how it looks before pushing to master

**Comment by coolapso** [comment]
Just few last notes, just pushed this commit https://github.com/pivpn/pivpn.io/commit/a6c138fd008c1051a01ee41298831d10af59a3e0, slightly changed the title and the code formatting. 

Just as general advice for any other project you can possibly contribute to, please first look at the existing code and try to keep the existing format. 

Also when making a PR, please fork the project, clone the project to your computer, make changes and then push to your fork, then make PR. 

website updated and live with latest changes.

**Comment by peppe8o** [comment]
Ok. I created my link by copying one of existing. Maybe I missed something.Thank you very much. GiuseppeInviato dal mio tablet Huawei-------- Messaggio originale --------Oggetto: Re: [pivpn/pivpn.io] Update index.html (#3)Da: 4s3ti A: "pivpn/pivpn.io" CC: peppe8o ,Mention 
Just few last notes, just pushed this commit a6c138f, slightly changed the title and the code formatting.
Just as general advice for any other project you can possibly contribute to, please first look at the existing code and try to keep the existing format.
Also when making a PR, please fork the project, clone the project to your computer, make changes and then push to your fork, then make PR.
website updated and live with latest changes.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/pivpn/pivpn.io/pull/3#issuecomment-719949003",
"url": "https://github.com/pivpn/pivpn.io/pull/3#issuecomment-719949003",
"name": "View Pull Request"
},
"description": "View this Pull Request on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by coolapso** [comment]
Its okay! :) thank you for your contribution!

**Pull request merged**
