### PR TITLE
fix: Minor documentation typo

### PR DESCRIPTION
**Pull request by somejeff**

### CODE REVIEW

**Comment by coolapso** [comment]
could you please amend your commit header to the following? 

> fix: Minor documentation typo

Thanks a lot

**Comment by somejeff** [comment]
Why did that pull, merge, amend, push look so messy?  😒

**Comment by coolapso** [comment]
you're using github web interface? Don't know how to do it through that .. but through cli 

```
git reset head master
git commit -a
``` 

should do the trick

**Comment by somejeff** [comment]
I think I'm just going to trash and restart.  I tried to amend, but for some reason had to merge first, then amend, which created a different commit.

**Comment by coolapso** [comment]
fine by me.

**Pull request closed without merging**
